### ISSUE TITLE
click_property help

### ISSUE THREAD

**Issue by UUoocl** [upgradeQ/obs-libre-macros#3]
Thank you for making this plug-in. obs-libre-macros has been helping me explore OBS with lua.  
I want to automate clicking the "Get Value" button in the Move Transition Plug-in's Move Video Capture Device filter. 
I can't get the click_property() function to work.  There is no response when I use this function.     

![image](https://github.com/upgradeQ/obs-libre-macros/assets/99063397/7286a953-b47a-4ae3-a9c6-5bd16fb5f1ab)

[This script](https://obsproject.com/forum/threads/how-to-enumerate-script-properties-in-lua.83406/) shows that the property is named "value_get".   I tried modifying this script to include the "obs_property_button_clicked" function, and the following error is returned.  

> Error in obs_property_button_clicked (arg 1), expected 'obs_property_t *' got 'cdata'

**Comment by upgradeQ** [comment]
@UUoocl What kind of response do you expect? Also what OBS Studio version do you use?  Maybe something has changed. In the code you mentioned, you are using obslua (SWIG bingings) instead of defining a proper ctype for ffi in LuaJIT, you should try to add this line `bool obs_property_button_clicked(obs_property_t *p, void *obj);` to ffi.cdef string as it defined in libobs [header](https://github.com/obsproject/obs-studio/blob/08f5a7bd4d62c3aae459b59a02eb927001d4fdbb/libobs/obs-properties.h#L305), and call `obsffi.obs_property_button_clicked(prop, fSource)`

**Comment by UUoocl** [comment]
Thank you for replying. The expected behavior is when the function runs the filter's settings are updated with all of the camera's current settings. 
The camera I'm using can rotate, and I want to use the camera's current position in the script.    
For example, before clicking the button the camera has a "pan" position of 14.
![image](https://github.com/upgradeQ/obs-libre-macros/assets/99063397/b0ce9994-dd7d-4032-b4b5-5d42635c6ff4)
Then the camera position moves.
After clicking the "Get Value" button, the filter is set to the new "pan" position of 94.
![image](https://github.com/upgradeQ/obs-libre-macros/assets/99063397/01e41998-faef-410b-8689-25cdbacf5e87)
 
 The "Get Filter" button calls[ this function](https://github.com/exeldro/obs-move-transition/blob/4a092594b9da63511540f00647fd81bddeef6bbe/move-directshow-filter.cpp#L932) to read the camera's properties.  
![image](https://github.com/upgradeQ/obs-libre-macros/assets/99063397/c07fa294-bc53-416f-a033-2ce41d221186)

I'm using OBS 29.1.3(64bit). 

Adding the line `bool obs_property_button_clicked(obs_property_t *p, void *obj);` as you suggested did correct the code!

Thank you very much!
